version: '3'

services:
    rabbit-1:
        image: rabbitmq:3.10.5-management-alpine
        hostname: rabbit-1
        container_name: rabbit-1
        ports:
            - '9000:15672'
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        networks:
            - gomc-broker
networks:
    gomc-broker: